#!/usr/bin/env bash
# ============================================================
# Mech Platform — Config Generator
# Usage: bash generate-config.sh [environment]
# Example: bash generate-config.sh production
# ============================================================

set -euo pipefail

ENV="${1:-development}"
FRONTEND_DIR="$(cd "$(dirname "$0")/frontend" 2>/dev/null && pwd || echo "./frontend")"
CONFIG_FILE="${FRONTEND_DIR}/config.js"

echo "🔧  Generating config.js for environment: ${ENV}"

# Read from environment variables with fallbacks
API_BASE="${API_BASE:-http://localhost:5000}"
WS_URL="${WS_URL:-http://localhost:5000}"
APP_VERSION="${APP_VERSION:-1.0.0}"
NEARBY_RADIUS_KM="${NEARBY_RADIUS_KM:-25}"

if [ "${ENV}" = "production" ]; then
  API_BASE="${API_BASE:-https://mech-backend.onrender.com}"
  WS_URL="${WS_URL:-https://mech-backend.onrender.com}"
fi

cat > "${CONFIG_FILE}" <<EOF
// ============================================================
// MECH PLATFORM — Runtime Configuration
// Generated by generate-config.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
// Environment: ${ENV}
// DO NOT edit manually — re-run generate-config.sh
// ============================================================

window.MechConfig = {
  API_BASE:    '${API_BASE}',
  WS_URL:      '${WS_URL}',
  APP_NAME:    'mech',
  APP_VERSION: '${APP_VERSION}',
  ENV:         '${ENV}',

  FEATURES: {
    GEOLOCATION:       true,
    WEBSOCKETS:        true,
    SMS_VERIFICATION:  true,
    VOICE_CALLS:       true,
    PUSH_NOTIFICATIONS: false,
  },

  MAPS: {
    TILE_URL:     'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    DEFAULT_LAT:  -1.2921,
    DEFAULT_LNG:  36.8219,
    DEFAULT_ZOOM: 13,
  },

  CURRENCY:        'KES',
  CURRENCY_LOCALE: 'en-KE',
  NEARBY_RADIUS_KM: ${NEARBY_RADIUS_KM},
  PAGE_SIZE:        20,
};
EOF

echo "✅  config.js written to ${CONFIG_FILE}"
echo ""
echo "    API_BASE : ${API_BASE}"
echo "    WS_URL   : ${WS_URL}"
echo "    ENV      : ${ENV}"
echo ""
